<?php
$title = 'Add Contact';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Please input name');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Please input email');

$phone_num = $form->get('phone_num');
$phone_num->setAttribute('class', 'form-control');
$phone_num->setAttribute('placeholder', 'Please input phone number');

$message = $form->get('message');
$message->setAttribute('class', 'form-control');
$message->setAttribute('placeholder', 'Please input message');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add',]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?=$this->formLabel($name)?>
    <?=$this->formElement($name)?>
    <?=$this->formElementErrors()->render($name,['class'=>'help-block'])?>
</div>
<div class="form-group">
    <?=$this->formLabel($email)?>
    <?=$this->formElement($email)?>
    <?=$this->formElementErrors()->render($email,['class'=>'help-block'])?>
</div>
<div class="form-group">
    <?=$this->formLabel($phone_num)?>
    <?=$this->formElement($phone_num)?>
    <?=$this->formElementErrors()->render($phone_num,['class'=>'help-block'])?>
</div>
<div class="form-group">
    <?=$this->formLabel($message)?>
    <?=$this->formElement($message)?>
    <?=$this->formElementErrors()->render($message,['class'=>'help-block'])?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();